- name: Power Off VM
  hosts: localhost
  tasks:
    - name: Power off VM
      community.vmware.vmware_guest:
        hostname: $vcenter_hostname
        datacenter: $datacenter_name
        folder: $folder_name
        name: $vm_name
        state: poweredoff
      register: poweroff_result # nom du registre

    - name: Show poweroff result
      debug:
        var: poweroff_result # affiche le contenu du registre
